# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -el {0}

    steps:
    - uses: actions/checkout@v4
    - name: Set up Anaconda
      uses: conda-incubator/setup-miniconda@v3.0.4
    - name: Install dependencies
      run: |
        conda env create -f environment.yml
        
    - name: Test with pytest
      run: |
        conda init
        conda activate slalom
        conda list
        export PYTHONPATH="."; python3 -m pytest
